import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
      {/*
        <nav className="fixed top-0 z-50 flex justify-between items-center p-5 py-10 w-full h-10 bg-yellow-300">
            <h1 className="font-mono text-3xl font-bold">MK</h1>
        </nav>
        */}
        {children}
      </body>
    </html>
  );
}
